### PR TITLE
Fix templatized dimension columns

### LINKED ISSUE #6: Custom dimensions do not appear in Dataset schema
Custom dimensions passed to the dimensions method do not appear to be added to the dataset schema as normal dimensions are. E.g.

```scala
val df = spark.read
    .format("com.crealytics.google.analytics")
    // ... auth stuff ...
    .option("startDate", "2016-11-10")
    .option("endDate", "2016-11-14")
    .option("dimensions", "dimension5,dimension6,dimension7")
    .option("queryIndividualDays", "true")
    .load()

df.select(
  col("dimension5").alias("cool dimension one"),
  col("dimension6").alias("neat dimensions two"),
  col("pageviews")
).orderBy(desc("dimension7"))

// org.apache.spark.sql.AnalysisException: cannot resolve '`dimension5`' given input columns
```

### PR DESCRIPTION
**Pull request by SebastianEdwards**
Templatized dimension columns were being filtered against user-defined `dimensions` before the expansion in `createSchemaFromColumns` is executed. This pull request moves this filtering further downstream. Fixes #6.

### CODE REVIEW

**Comment by nightscape** [comment]
Hey @SebastianEdwards, thanks a lot for taking action here!
I haven't thought through the changes yet, but Travis can't compile the code as is.
Did you check in all changes?

**Comment by SebastianEdwards** [comment]
@nightscape: I've recommitted now and we're green. Thanks for taking the time to consider this PR.

**Comment by nightscape** [comment]
Hi @SebastianEdwards,

I took some time to dig deeper into this, and made some bigger changes to the master branch which should solve your use case.
The problem with this PR was, that it could have led to the case that in the options you select dimensions `A` and `B`, but the `schema` of the resulting DataFrame would contain all dimensions, e.g. `A`, `B` and `C`. If you then did something like `df.select("C")` you would probably have run into some internal Spark casting error.
I removed the dimension selection from the initial options, you should now be able to select any dimension at any time (with some minor constraints, see README).

Could you checkout the current master version and see if all is working on your side?
If so, I'll release `1.1.0`.

Hope I didn't step on your toes, but I was in Spark fever & flow and reasoned that it takes more time to explain the issue than fixing it myself.
I'm still happy about all contributions!

**Comment by SebastianEdwards** [comment]
No toe-stepping at all mate - just happy to have the use case supported! The new API looks like a big improvement. Really cool having dimensions and metrics defined in the same place.

Seems to work fine pulling custom dimensions. However, the "dimensions before metrics" check seems to break when more than one column is aliased (a single alias seems to work) E.g.

```scala
display(df.select(
  col("date"),
  col("dimension5").alias("client id"),
  col("dimension6").alias("session id"),
  col("pagePath"),
  col("pageviews")
))

IllegalArgumentException: You need to put dimension columns at the beginning e.g. df.select(col("dimension5"), col("date"), col("pagePath"), col("dimension6"), col("pageviews"))
```

**Comment by nightscape** [comment]
Ok, it looks like my assumption that the order in the provided `requiredColumns: Seq[String]` mirrors the order in the `df.select` is completely wrong. I'm checking if there's another way to handle this.

**Comment by nightscape** [comment]
I just pushed another commit that gets rid of the necessity to order columns and hopefully also handles aliases correctly. Can you try again?

**Comment by SebastianEdwards** [comment]
@nightscape: Nice one 👍  working like a dream

**Pull request closed without merging**
